apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ipprofilemly
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.144/32
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ipcvmly
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.145/32
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ippool
  namespace: metallb-system
spec:
  ipAddressPools:
  - ipprofilemly
  - ipcvmly
