# How to use, this is useless without downloading istioctl binaries and files
# 1. curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.22.3 TARGET_ARCH=x86_64 sh -
# 2. cd istio-1.22.3/
# 3. export PATH=$PWD/bin:$PATH
# 4. ln -s ABSOLUTE_PATH_TO_THIS_YAML_FILE manifests/profile/NAME_OF_THIS_FILE
# 5. istioctl install --set profile=manifests/profiles/NAME_OF_THIS_FILE
#
# If you want to cleanup:
# 1. istioctl uninstall --purge
#

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  hub: docker.io/istio
  tag: 1.22.3

  # Turn on default components: base, pilot, and ingress gateway
  components:
    base:
      enabled: true
    pilot:
      enabled: true
    # Istio Gateway feature
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
    - name: istio-ingressgateway-profile
      enabled: true
      k8s:
        serviceAnnotations:
          metallb.universe.tf/address-pool:  ipprofilemly
        overlays: # This object will modify default properties of the component
            - kind: HorizontalPodAutoscaler
              name: istio-ingressgateway-profile
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-profile
                - path: metadata.labels.istio
                  value: ingressgateway-profile
                - path: spec.scaleTargetRef.name
                  value: istio-ingressgateway-profile
            - kind: Deployment
              name: istio-ingressgateway-profile
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-profile  # Change the label to istio-ingressgateway-profile
                - path: metadata.labels.istio
                  value: ingressgateway-profile
                - path: spec.selector.matchLabels.app
                  value: istio-ingressgateway-profile
                - path: spec.selector.matchLabels.istio
                  value: ingressgateway-profile
                - path: spec.template.metadata.labels.app
                  value: istio-ingressgateway-profile
                - path: spec.template.metadata.labels.istio
                  value: ingressgateway-profile
            - kind: Service
              name: istio-ingressgateway-profile
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-profile
                - path: metadata.labels.istio
                  value: ingressgateway-profile
                - path: spec.selector.app
                  value: istio-ingressgateway-profile
                - path: spec.selector.istio
                  value: ingressgateway-profile
    - name: istio-ingressgateway-cv
      enabled: true
      k8s:
        serviceAnnotations:
          metallb.universe.tf/address-pool:  ipcvmly
        overlays: # This object will modify default properties of the component
            - kind: HorizontalPodAutoscaler
              name: istio-ingressgateway-cv
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-cv
                - path: metadata.labels.istio
                  value: ingressgateway-cv
                - path: spec.scaleTargetRef.name
                  value: istio-ingressgateway-cv
            - kind: Deployment
              name: istio-ingressgateway-cv
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-cv  # Change the label to istio-ingressgateway-cv
                - path: metadata.labels.istio
                  value: ingressgateway-cv
                - path: spec.selector.matchLabels.app
                  value: istio-ingressgateway-cv
                - path: spec.selector.matchLabels.istio
                  value: ingressgateway-cv
                - path: spec.template.metadata.labels.app
                  value: istio-ingressgateway-cv
                - path: spec.template.metadata.labels.istio
                  value: ingressgateway-cv
            - kind: Service
              name: istio-ingressgateway-cv
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-cv
                - path: metadata.labels.istio
                  value: ingressgateway-cv
                - path: spec.selector.app
                  value: istio-ingressgateway-cv
                - path: spec.selector.istio
                  value: ingressgateway-cv
    egressGateways:
    - name: istio-egressgateway
      enabled: false
    - name: istio-egressgateway-profile
      enabled: false
    - name: istio-egressgateway-cv
      enabled: false

  # Most default values come from the helm chart's values.yaml
  # Below are the things that differ
  values:
    defaultRevision: ""
    global:
      istioNamespace: istio-system
      configValidation: true
    gateways:
      istio-ingressgateway: {}
      istio-egressgateway: {}
